<?php

namespace App\AppTemplate;

/**
 * @author  Emmanuel Oppong-Sarpong
 * @since   February 8, 2019
 * @link    https://github.com/Sarps/bulk-mailer
 * @version 1.0.0
 */
class AppTemplate extends \Sarps\LaunchPad
{

    public function __construct()
    {
        parent::__construct();

        //Your code goes here

    }

    /**
     * @return string
     */
    public function email()
    {
        return parent::email(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function view()
    {
        return "ViewName";
    }

    /**
     * @return string
     */
    public function subject()
    {
        return "Example Subject";
    }

    /**
     * @return array
     */
    public function addresses()
    {
        return array(
            "receipient1@example.com",
            "receipient2@example.com",
        );
    }

    public function mailingStartCallback()
    {
        // $this->warning('AppTemplate mailing started, make sure you have good internet connection');
    }

    public function mailSentCallback($index, $email, $data)
    {
        // $logger = new AppTemplateLogger();
        // $logger->log('sent', $email, json_encode($data) );
    }

    public function mailFailedCallback($index, $email, $data)
    {
        // $logger = new AppTemplateLogger();
        // $logger->log('not sent', $email, json_encode($data));
    }

    public function mailingCompleteCallback()
    {
        // $this->success('AppTemplate mailing complete. Check the logs, if any, to verify all mails sent');
    }

}